### ISSUE TITLE
Sample tests are failing!

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-game-servers#78]
Looking at this PR:
https://github.com/googleapis/nodejs-game-servers/pull/77#pullrequestreview-439471193

It doesn't change anything meaningful, and the tests are failing 😭

**Comment by Laremere** [comment]
I'll take this.

**Comment by Laremere** [comment]
The error is this:
`

  Game Servers Create Cluster Test
(node:331) UnhandledPromiseRejectionWarning: Error: 5 NOT_FOUND: agones namespace "agones-system" does not exist on the cluster "projects/1046198160504/locations/us-west1-a/clusters/grpc-bug-cluster"
    at Object.callErrorFromStatus (/tmpfs/src/github/nodejs-game-servers/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus (/tmpfs/src/github/nodejs-game-servers/node_modules/@grpc/grpc-js/build/src/client.js:175:52)
    at Object.onReceiveStatus (/tmpfs/src/github/nodejs-game-servers/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:341:141)
    at Object.onReceiveStatus (/tmpfs/src/github/nodejs-game-servers/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:304:181)
    at Http2CallStream.outputStatus (/tmpfs/src/github/nodejs-game-servers/node_modules/@grpc/grpc-js/build/src/call-stream.js:116:74)
    at Http2CallStream.maybeOutputStatus (/tmpfs/src/github/nodejs-game-servers/node_modules/@grpc/grpc-js/build/src/call-stream.js:155:22)
    at Http2CallStream.endCall (/tmpfs/src/github/nodejs-game-servers/node_modules/@grpc/grpc-js/build/src/call-stream.js:141:18)
    at Http2CallStream.handleTrailers (/tmpfs/src/github/nodejs-game-servers/node_modules/@grpc/grpc-js/build/src/call-stream.js:273:14)
    at ClientHttp2Stream.emit (events.js:198:13)
    at emit (internal/http2/core.js:265:8)
(node:331) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:331) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    1) should create a Game Server cluster
    2) "after all" hook for "should create a Game Server cluster"
`

This is because it is trying to connect a GKE cluster as a gcgs cluster, but validation that the GKE cluster has agones installed on it was recently added, so the test cluster needs to have it installed, or the samples switched to using a test cluster which does have it installed.

**Comment by Laremere** [comment]
Currently determining who is going to work on the nodejs samples, once that's figured out, this will be the first task associated with that.
